#define IOCTL_START_NUM 0x80
#define IOCTL_NUM1 IOCTL_START_NUM+1
#define IOCTL_NUM2 IOCTL_START_NUM+2
#define IOCTL_NUM3 IOCTL_START_NUM+3
#define IOCTL_NUM4 IOCTL_START_NUM+4

#define SIMPLE_IOCTL_NUM 'z'
#define KU_MSGGET _IOWR(SIMPLE_IOCTL_NUM,IOCTL_NUM1,unsigned long *)
#define KU_MSGCLOSE _IOWR(SIMPLE_IOCTL_NUM,IOCTL_NUM2,unsigned long *)
#define KU_MSGSND _IOWR(SIMPLE_IOCTL_NUM,IOCTL_NUM3,unsigned long *)
#define KU_MSGRCV _IOWR(SIMPLE_IOCTL_NUM,IOCTL_NUM4,unsigned long *)


#define KUIPC_MAXMSG 10
#define KUIPC_MAXVOL 132*10
#define KU_IPC_CREAT 2
#define KU_IPC_EXCL 4
#define KU_IPC_NOWAIT 8
#define KU_IPC_NOERROR 16

